#-------------------------------------------------
#
# Project created by QtCreator 2019-07-17T12:09:40
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Kinect2QtTest
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += \
        main.cpp \
        widget.cpp \
    main.cpp \
    widget.cpp \
    main.cpp \
    widget.cpp

HEADERS += \
        widget.h \
    Kinect2SKDInc/Kinect.Face.h \
    Kinect2SKDInc/Kinect.h \
    Kinect2SKDInc/Kinect.INPC.h \
    Kinect2SKDInc/Kinect.VisualGestureBuilder.h \
    Kinect2SKDInc/NuiKinectFusionApi.h \
    Kinect2SKDInc/NuiKinectFusionBase.h \
    Kinect2SKDInc/NuiKinectFusionCameraPoseFinder.h \
    Kinect2SKDInc/NuiKinectFusionColorVolume.h \
    Kinect2SKDInc/NuiKinectFusionDepthProcessor.h \
    Kinect2SKDInc/NuiKinectFusionVolume.h \
    widget.h \
    Kinect2SKDInc/Kinect.Face.h \
    Kinect2SKDInc/Kinect.h \
    Kinect2SKDInc/Kinect.INPC.h \
    Kinect2SKDInc/Kinect.VisualGestureBuilder.h \
    Kinect2SKDInc/NuiKinectFusionApi.h \
    Kinect2SKDInc/NuiKinectFusionBase.h \
    Kinect2SKDInc/NuiKinectFusionCameraPoseFinder.h \
    Kinect2SKDInc/NuiKinectFusionColorVolume.h \
    Kinect2SKDInc/NuiKinectFusionDepthProcessor.h \
    Kinect2SKDInc/NuiKinectFusionVolume.h \
    OpenCVInc/opencv/cv.h \
    OpenCVInc/opencv/cv.hpp \
    OpenCVInc/opencv/cvaux.h \
    OpenCVInc/opencv/cvaux.hpp \
    OpenCVInc/opencv/cvwimage.h \
    OpenCVInc/opencv/cxcore.h \
    OpenCVInc/opencv/cxcore.hpp \
    OpenCVInc/opencv/cxeigen.hpp \
    OpenCVInc/opencv/cxmisc.h \
    OpenCVInc/opencv/highgui.h \
    OpenCVInc/opencv/ml.h \
    OpenCVInc/opencv2/calib3d/calib3d.hpp \
    OpenCVInc/opencv2/calib3d/calib3d_c.h \
    OpenCVInc/opencv2/core/cuda/detail/color_detail.hpp \
    OpenCVInc/opencv2/core/cuda/detail/reduce.hpp \
    OpenCVInc/opencv2/core/cuda/detail/reduce_key_val.hpp \
    OpenCVInc/opencv2/core/cuda/detail/transform_detail.hpp \
    OpenCVInc/opencv2/core/cuda/detail/type_traits_detail.hpp \
    OpenCVInc/opencv2/core/cuda/detail/vec_distance_detail.hpp \
    OpenCVInc/opencv2/core/cuda/block.hpp \
    OpenCVInc/opencv2/core/cuda/border_interpolate.hpp \
    OpenCVInc/opencv2/core/cuda/color.hpp \
    OpenCVInc/opencv2/core/cuda/common.hpp \
    OpenCVInc/opencv2/core/cuda/datamov_utils.hpp \
    OpenCVInc/opencv2/core/cuda/dynamic_smem.hpp \
    OpenCVInc/opencv2/core/cuda/emulation.hpp \
    OpenCVInc/opencv2/core/cuda/filters.hpp \
    OpenCVInc/opencv2/core/cuda/funcattrib.hpp \
    OpenCVInc/opencv2/core/cuda/functional.hpp \
    OpenCVInc/opencv2/core/cuda/limits.hpp \
    OpenCVInc/opencv2/core/cuda/reduce.hpp \
    OpenCVInc/opencv2/core/cuda/saturate_cast.hpp \
    OpenCVInc/opencv2/core/cuda/scan.hpp \
    OpenCVInc/opencv2/core/cuda/simd_functions.hpp \
    OpenCVInc/opencv2/core/cuda/transform.hpp \
    OpenCVInc/opencv2/core/cuda/type_traits.hpp \
    OpenCVInc/opencv2/core/cuda/utility.hpp \
    OpenCVInc/opencv2/core/cuda/vec_distance.hpp \
    OpenCVInc/opencv2/core/cuda/vec_math.hpp \
    OpenCVInc/opencv2/core/cuda/vec_traits.hpp \
    OpenCVInc/opencv2/core/cuda/warp.hpp \
    OpenCVInc/opencv2/core/cuda/warp_reduce.hpp \
    OpenCVInc/opencv2/core/cuda/warp_shuffle.hpp \
    OpenCVInc/opencv2/core/hal/hal.hpp \
    OpenCVInc/opencv2/core/hal/interface.h \
    OpenCVInc/opencv2/core/hal/intrin.hpp \
    OpenCVInc/opencv2/core/hal/intrin_avx.hpp \
    OpenCVInc/opencv2/core/hal/intrin_cpp.hpp \
    OpenCVInc/opencv2/core/hal/intrin_forward.hpp \
    OpenCVInc/opencv2/core/hal/intrin_neon.hpp \
    OpenCVInc/opencv2/core/hal/intrin_sse.hpp \
    OpenCVInc/opencv2/core/hal/intrin_sse_em.hpp \
    OpenCVInc/opencv2/core/hal/intrin_vsx.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_clamdblas.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_clamdfft.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_core.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_gl.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_svm_20.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp \
    OpenCVInc/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp \
    OpenCVInc/opencv2/core/opencl/ocl_defs.hpp \
    OpenCVInc/opencv2/core/opencl/opencl_info.hpp \
    OpenCVInc/opencv2/core/opencl/opencl_svm.hpp \
    OpenCVInc/opencv2/core/utils/filesystem.hpp \
    OpenCVInc/opencv2/core/utils/logger.defines.hpp \
    OpenCVInc/opencv2/core/utils/logger.hpp \
    OpenCVInc/opencv2/core/utils/trace.hpp \
    OpenCVInc/opencv2/core/affine.hpp \
    OpenCVInc/opencv2/core/base.hpp \
    OpenCVInc/opencv2/core/bindings_utils.hpp \
    OpenCVInc/opencv2/core/bufferpool.hpp \
    OpenCVInc/opencv2/core/check.hpp \
    OpenCVInc/opencv2/core/core.hpp \
    OpenCVInc/opencv2/core/core_c.h \
    OpenCVInc/opencv2/core/cuda.hpp \
    OpenCVInc/opencv2/core/cuda.inl.hpp \
    OpenCVInc/opencv2/core/cuda_stream_accessor.hpp \
    OpenCVInc/opencv2/core/cuda_types.hpp \
    OpenCVInc/opencv2/core/cv_cpu_dispatch.h \
    OpenCVInc/opencv2/core/cv_cpu_helper.h \
    OpenCVInc/opencv2/core/cvdef.h \
    OpenCVInc/opencv2/core/cvstd.hpp \
    OpenCVInc/opencv2/core/cvstd.inl.hpp \
    OpenCVInc/opencv2/core/directx.hpp \
    OpenCVInc/opencv2/core/eigen.hpp \
    OpenCVInc/opencv2/core/fast_math.hpp \
    OpenCVInc/opencv2/core/ippasync.hpp \
    OpenCVInc/opencv2/core/mat.hpp \
    OpenCVInc/opencv2/core/mat.inl.hpp \
    OpenCVInc/opencv2/core/matx.hpp \
    OpenCVInc/opencv2/core/neon_utils.hpp \
    OpenCVInc/opencv2/core/ocl.hpp \
    OpenCVInc/opencv2/core/ocl_genbase.hpp \
    OpenCVInc/opencv2/core/opengl.hpp \
    OpenCVInc/opencv2/core/operations.hpp \
    OpenCVInc/opencv2/core/optim.hpp \
    OpenCVInc/opencv2/core/ovx.hpp \
    OpenCVInc/opencv2/core/persistence.hpp \
    OpenCVInc/opencv2/core/ptr.inl.hpp \
    OpenCVInc/opencv2/core/saturate.hpp \
    OpenCVInc/opencv2/core/softfloat.hpp \
    OpenCVInc/opencv2/core/sse_utils.hpp \
    OpenCVInc/opencv2/core/traits.hpp \
    OpenCVInc/opencv2/core/types.hpp \
    OpenCVInc/opencv2/core/types_c.h \
    OpenCVInc/opencv2/core/utility.hpp \
    OpenCVInc/opencv2/core/va_intel.hpp \
    OpenCVInc/opencv2/core/version.hpp \
    OpenCVInc/opencv2/core/vsx_utils.hpp \
    OpenCVInc/opencv2/core/wimage.hpp \
    OpenCVInc/opencv2/dnn/utils/inference_engine.hpp \
    OpenCVInc/opencv2/dnn/all_layers.hpp \
    OpenCVInc/opencv2/dnn/dict.hpp \
    OpenCVInc/opencv2/dnn/dnn.hpp \
    OpenCVInc/opencv2/dnn/dnn.inl.hpp \
    OpenCVInc/opencv2/dnn/layer.details.hpp \
    OpenCVInc/opencv2/dnn/layer.hpp \
    OpenCVInc/opencv2/dnn/shape_utils.hpp \
    OpenCVInc/opencv2/features2d/hal/interface.h \
    OpenCVInc/opencv2/features2d/features2d.hpp \
    OpenCVInc/opencv2/flann/all_indices.h \
    OpenCVInc/opencv2/flann/allocator.h \
    OpenCVInc/opencv2/flann/any.h \
    OpenCVInc/opencv2/flann/autotuned_index.h \
    OpenCVInc/opencv2/flann/composite_index.h \
    OpenCVInc/opencv2/flann/config.h \
    OpenCVInc/opencv2/flann/defines.h \
    OpenCVInc/opencv2/flann/dist.h \
    OpenCVInc/opencv2/flann/dummy.h \
    OpenCVInc/opencv2/flann/dynamic_bitset.h \
    OpenCVInc/opencv2/flann/flann.hpp \
    OpenCVInc/opencv2/flann/flann_base.hpp \
    OpenCVInc/opencv2/flann/general.h \
    OpenCVInc/opencv2/flann/ground_truth.h \
    OpenCVInc/opencv2/flann/hdf5.h \
    OpenCVInc/opencv2/flann/heap.h \
    OpenCVInc/opencv2/flann/hierarchical_clustering_index.h \
    OpenCVInc/opencv2/flann/index_testing.h \
    OpenCVInc/opencv2/flann/kdtree_index.h \
    OpenCVInc/opencv2/flann/kdtree_single_index.h \
    OpenCVInc/opencv2/flann/kmeans_index.h \
    OpenCVInc/opencv2/flann/linear_index.h \
    OpenCVInc/opencv2/flann/logger.h \
    OpenCVInc/opencv2/flann/lsh_index.h \
    OpenCVInc/opencv2/flann/lsh_table.h \
    OpenCVInc/opencv2/flann/matrix.h \
    OpenCVInc/opencv2/flann/miniflann.hpp \
    OpenCVInc/opencv2/flann/nn_index.h \
    OpenCVInc/opencv2/flann/object_factory.h \
    OpenCVInc/opencv2/flann/params.h \
    OpenCVInc/opencv2/flann/random.h \
    OpenCVInc/opencv2/flann/result_set.h \
    OpenCVInc/opencv2/flann/sampling.h \
    OpenCVInc/opencv2/flann/saving.h \
    OpenCVInc/opencv2/flann/simplex_downhill.h \
    OpenCVInc/opencv2/flann/timer.h \
    OpenCVInc/opencv2/highgui/highgui.hpp \
    OpenCVInc/opencv2/highgui/highgui_c.h \
    OpenCVInc/opencv2/imgcodecs/imgcodecs.hpp \
    OpenCVInc/opencv2/imgcodecs/imgcodecs_c.h \
    OpenCVInc/opencv2/imgcodecs/ios.h \
    OpenCVInc/opencv2/imgproc/detail/distortion_model.hpp \
    OpenCVInc/opencv2/imgproc/hal/hal.hpp \
    OpenCVInc/opencv2/imgproc/hal/interface.h \
    OpenCVInc/opencv2/imgproc/imgproc.hpp \
    OpenCVInc/opencv2/imgproc/imgproc_c.h \
    OpenCVInc/opencv2/imgproc/types_c.h \
    OpenCVInc/opencv2/ml/ml.hpp \
    OpenCVInc/opencv2/ml/ml.inl.hpp \
    OpenCVInc/opencv2/objdetect/detection_based_tracker.hpp \
    OpenCVInc/opencv2/objdetect/objdetect.hpp \
    OpenCVInc/opencv2/objdetect/objdetect_c.h \
    OpenCVInc/opencv2/photo/cuda.hpp \
    OpenCVInc/opencv2/photo/photo.hpp \
    OpenCVInc/opencv2/photo/photo_c.h \
    OpenCVInc/opencv2/shape/emdL1.hpp \
    OpenCVInc/opencv2/shape/hist_cost.hpp \
    OpenCVInc/opencv2/shape/shape.hpp \
    OpenCVInc/opencv2/shape/shape_distance.hpp \
    OpenCVInc/opencv2/shape/shape_transformer.hpp \
    OpenCVInc/opencv2/stitching/detail/autocalib.hpp \
    OpenCVInc/opencv2/stitching/detail/blenders.hpp \
    OpenCVInc/opencv2/stitching/detail/camera.hpp \
    OpenCVInc/opencv2/stitching/detail/exposure_compensate.hpp \
    OpenCVInc/opencv2/stitching/detail/matchers.hpp \
    OpenCVInc/opencv2/stitching/detail/motion_estimators.hpp \
    OpenCVInc/opencv2/stitching/detail/seam_finders.hpp \
    OpenCVInc/opencv2/stitching/detail/timelapsers.hpp \
    OpenCVInc/opencv2/stitching/detail/util.hpp \
    OpenCVInc/opencv2/stitching/detail/util_inl.hpp \
    OpenCVInc/opencv2/stitching/detail/warpers.hpp \
    OpenCVInc/opencv2/stitching/detail/warpers_inl.hpp \
    OpenCVInc/opencv2/stitching/warpers.hpp \
    OpenCVInc/opencv2/superres/optical_flow.hpp \
    OpenCVInc/opencv2/video/background_segm.hpp \
    OpenCVInc/opencv2/video/tracking.hpp \
    OpenCVInc/opencv2/video/tracking_c.h \
    OpenCVInc/opencv2/video/video.hpp \
    OpenCVInc/opencv2/videoio/cap_ios.h \
    OpenCVInc/opencv2/videoio/registry.hpp \
    OpenCVInc/opencv2/videoio/videoio.hpp \
    OpenCVInc/opencv2/videoio/videoio_c.h \
    OpenCVInc/opencv2/videostab/deblurring.hpp \
    OpenCVInc/opencv2/videostab/fast_marching.hpp \
    OpenCVInc/opencv2/videostab/fast_marching_inl.hpp \
    OpenCVInc/opencv2/videostab/frame_source.hpp \
    OpenCVInc/opencv2/videostab/global_motion.hpp \
    OpenCVInc/opencv2/videostab/inpainting.hpp \
    OpenCVInc/opencv2/videostab/log.hpp \
    OpenCVInc/opencv2/videostab/motion_core.hpp \
    OpenCVInc/opencv2/videostab/motion_stabilizing.hpp \
    OpenCVInc/opencv2/videostab/optical_flow.hpp \
    OpenCVInc/opencv2/videostab/outlier_rejection.hpp \
    OpenCVInc/opencv2/videostab/ring_buffer.hpp \
    OpenCVInc/opencv2/videostab/stabilizer.hpp \
    OpenCVInc/opencv2/videostab/wobble_suppression.hpp \
    OpenCVInc/opencv2/calib3d.hpp \
    OpenCVInc/opencv2/core.hpp \
    OpenCVInc/opencv2/cvconfig.h \
    OpenCVInc/opencv2/dnn.hpp \
    OpenCVInc/opencv2/features2d.hpp \
    OpenCVInc/opencv2/flann.hpp \
    OpenCVInc/opencv2/highgui.hpp \
    OpenCVInc/opencv2/imgcodecs.hpp \
    OpenCVInc/opencv2/imgproc.hpp \
    OpenCVInc/opencv2/ml.hpp \
    OpenCVInc/opencv2/objdetect.hpp \
    OpenCVInc/opencv2/opencv.hpp \
    OpenCVInc/opencv2/opencv_modules.hpp \
    OpenCVInc/opencv2/photo.hpp \
    OpenCVInc/opencv2/shape.hpp \
    OpenCVInc/opencv2/stitching.hpp \
    OpenCVInc/opencv2/superres.hpp \
    OpenCVInc/opencv2/video.hpp \
    OpenCVInc/opencv2/videoio.hpp \
    OpenCVInc/opencv2/videostab.hpp \
    OpenCVInc/opencv2/world.hpp \
    widget.h

FORMS += \
        widget.ui

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.Face
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.Face

INCLUDEPATH += $$PWD/Kinect2SKDLib/x64
DEPENDPATH += $$PWD/Kinect2SKDLib/x64

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.Fusion
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.Fusion

INCLUDEPATH += $$PWD/Kinect2SKDLib/x64
DEPENDPATH += $$PWD/Kinect2SKDLib/x64

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20

INCLUDEPATH += $$PWD/Kinect2SKDLib/x64
DEPENDPATH += $$PWD/Kinect2SKDLib/x64

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.VisualGestureBuilder
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/Kinect2SKDLib/x64/ -lKinect20.VisualGestureBuilder

INCLUDEPATH += $$PWD/Kinect2SKDLib/x64
DEPENDPATH += $$PWD/Kinect2SKDLib/x64

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/OpenCVLib/ -lopencv_world346
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/OpenCVLib/ -lopencv_world346d

INCLUDEPATH += $$PWD/OpenCVLib
DEPENDPATH += $$PWD/OpenCVLib

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/OpenCVLib/ -lopencv_world346
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/OpenCVLib/ -lopencv_world346d

INCLUDEPATH += $$PWD/OpenCVLib
DEPENDPATH += $$PWD/OpenCVLib

INCLUDEPATH += $$PWD/OpenCVInc/opencv\
               $$PWD/OpenCVInc/opencv2\
               $$PWD/OpenCVInc\


#PCL
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/include/pcl-1.8)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/include/pcl-1.8/pcl)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/Boost/include/boost-1_61)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/Eigen/eigen3)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/FLANN/include)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/FLANN/include/flann)\
INCLUDEPATH += $$quote(C:\Program Files\OpenNI2/Include)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/Qhull/include)\
INCLUDEPATH += $$quote(C:\Program Files\PCL1.8.0/3rdParty/VTK/include/vtk-7.0)\



###########################################################Release
#else:
CONFIG(release,debug|release):
{
LIBS += -L$$quote(C:\Program Files\PCL1.8.0/lib)\
#-lpcl_apps_release\
-lpcl_common_release\
-lpcl_features_release\
-lpcl_filters_release\
-lpcl_io_release\
-lpcl_io_ply_release\
-lpcl_kdtree_release\
-lpcl_keypoints_release\
-lpcl_ml_release\
-lpcl_octree_release\
-lpcl_outofcore_release\
-lpcl_people_release\
-lpcl_recognition_release\
-lpcl_registration_release\
-lpcl_sample_consensus_release\
-lpcl_search_release\
-lpcl_segmentation_release\
#-lpcl_simulation_release\
-lpcl_stereo_release\
-lpcl_surface_release\
-lpcl_tracking_release\
-lpcl_visualization_release\

LIBS += -L$$quote(C:\Program Files\PCL1.8.0/3rdParty/Boost/lib)\
-llibboost_atomic-vc140-mt-1_61\
-llibboost_chrono-vc140-mt-1_61\
-llibboost_container-vc140-mt-1_61\
-llibboost_context-vc140-mt-1_61\
-llibboost_coroutine-vc140-mt-1_61\
-llibboost_date_time-vc140-mt-1_61\
-llibboost_exception-vc140-mt-1_61\
-llibboost_filesystem-vc140-mt-1_61\
-llibboost_graph-vc140-mt-1_61\
-llibboost_iostreams-vc140-mt-1_61\
-llibboost_locale-vc140-mt-1_61\
-llibboost_log-vc140-mt-1_61\
-llibboost_log_setup-vc140-mt-1_61\
-llibboost_math_c99-vc140-mt-1_61\
-llibboost_math_c99f-vc140-mt-1_61\
-llibboost_math_c99l-vc140-mt-1_61\
-llibboost_math_tr1-vc140-mt-1_61\
-llibboost_math_tr1f-vc140-mt-1_61\
-llibboost_math_tr1l-vc140-mt-1_61\
-llibboost_mpi-vc140-mt-1_61\
-llibboost_prg_exec_monitor-vc140-mt-1_61\
-llibboost_program_options-vc140-mt-1_61\
-llibboost_random-vc140-mt-1_61\
-llibboost_regex-vc140-mt-1_61\
-llibboost_serialization-vc140-mt-1_61\
-llibboost_signals-vc140-mt-1_61\
-llibboost_system-vc140-mt-1_61\
-llibboost_test_exec_monitor-vc140-mt-1_61\
-llibboost_thread-vc140-mt-1_61\
-llibboost_timer-vc140-mt-1_61\
-llibboost_unit_test_framework-vc140-mt-1_61\
-llibboost_wave-vc140-mt-1_61\
-llibboost_wserialization-vc140-mt-1_61

LIBS += -L$$quote(C:\Program Files\PCL1.8.0/3rdParty/FLANN/lib)\
-lflann\
-lflann_cpp_s\
-lflann_s

LIBS += -L$$quote(C:\Program Files\OpenNI2/Lib)\
-lOpenNI2

LIBS += -L$$quote(C:\Program Files\PCL1.8.0/3rdParty/Qhull/lib)\
-lqhull\
-lqhullcpp\
-lqhullstatic\
-lqhullstatic_r\
-lqhull_p\
-lqhull_r

LIBS += -L$$quote(C:\Program Files\PCL1.8.0\3rdParty\VTK\lib)\
-lvtkalglib-7.0\
-lvtkChartsCore-7.0\
-lvtkCommonColor-7.0\
-lvtkCommonComputationalGeometry-7.0\
-lvtkCommonCore-7.0\
-lvtkCommonDataModel-7.0\
-lvtkCommonExecutionModel-7.0\
-lvtkCommonMath-7.0\
-lvtkCommonMisc-7.0\
-lvtkCommonSystem-7.0\
-lvtkCommonTransforms-7.0\
-lvtkDICOMParser-7.0\
-lvtkDomainsChemistry-7.0\
#-lvtkDomainsChemistryOpenGL-7.0\
-lvtkexoIIc-7.0\
-lvtkexpat-7.0\
-lvtkFiltersAMR-7.0\
-lvtkFiltersCore-7.0\
-lvtkFiltersExtraction-7.0\
-lvtkFiltersFlowPaths-7.0\
-lvtkFiltersGeneral-7.0\
-lvtkFiltersGeneric-7.0\
-lvtkFiltersGeometry-7.0\
-lvtkFiltersHybrid-7.0\
-lvtkFiltersHyperTree-7.0\
-lvtkFiltersImaging-7.0\
-lvtkFiltersModeling-7.0\
-lvtkFiltersParallel-7.0\
-lvtkFiltersParallelImaging-7.0\
-lvtkFiltersProgrammable-7.0\
-lvtkFiltersSelection-7.0\
-lvtkFiltersSMP-7.0\
-lvtkFiltersSources-7.0\
-lvtkFiltersStatistics-7.0\
-lvtkFiltersTexture-7.0\
-lvtkFiltersVerdict-7.0\
-lvtkfreetype-7.0\
-lvtkGeovisCore-7.0\
#-lvtkglew-7.0\
#-lvtkGUISupportQt-7.0\
#-lvtkGUISupportQtSQL-7.0\
-lvtkhdf5-7.0\
-lvtkhdf5_hl-7.0\
-lvtkImagingColor-7.0\
-lvtkImagingCore-7.0\
-lvtkImagingFourier-7.0\
-lvtkImagingGeneral-7.0\
-lvtkImagingHybrid-7.0\
-lvtkImagingMath-7.0\
-lvtkImagingMorphological-7.0\
-lvtkImagingSources-7.0\
-lvtkImagingStatistics-7.0\
-lvtkImagingStencil-7.0\
-lvtkInfovisCore-7.0\
-lvtkInfovisLayout-7.0\
-lvtkInteractionImage-7.0\
-lvtkInteractionStyle-7.0\
-lvtkInteractionWidgets-7.0\
-lvtkIOAMR-7.0\
-lvtkIOCore-7.0\
-lvtkIOEnSight-7.0\
-lvtkIOExodus-7.0\
-lvtkIOExport-7.0\
-lvtkIOGeometry-7.0\
-lvtkIOImage-7.0\
-lvtkIOImport-7.0\
-lvtkIOInfovis-7.0\
-lvtkIOLegacy-7.0\
-lvtkIOLSDyna-7.0\
-lvtkIOMINC-7.0\
-lvtkIOMovie-7.0\
-lvtkIONetCDF-7.0\
-lvtkIOParallel-7.0\
-lvtkIOParallelXML-7.0\
-lvtkIOPLY-7.0\
-lvtkIOSQL-7.0\
-lvtkIOVideo-7.0\
-lvtkIOXML-7.0\
-lvtkIOXMLParser-7.0\
-lvtkjpeg-7.0\
-lvtkjsoncpp-7.0\
-lvtklibxml2-7.0\
-lvtkmetaio-7.0\
-lvtkNetCDF-7.0\
-lvtkNetCDF_cxx-7.0\
-lvtkoggtheora-7.0\
-lvtkParallelCore-7.0\
-lvtkpng-7.0\
-lvtkproj4-7.0\
-lvtkRenderingAnnotation-7.0\
-lvtkRenderingContext2D-7.0\
-lvtkRenderingContextOpenGL-7.0\
-lvtkRenderingCore-7.0\
-lvtkRenderingFreeType-7.0\
-lvtkRenderingImage-7.0\
-lvtkRenderingLabel-7.0\
-lvtkRenderingLOD-7.0\
-lvtkRenderingOpenGL-7.0\
#-lvtkRenderingQt-7.0\
-lvtkRenderingVolume-7.0\
-lvtkRenderingVolumeOpenGL-7.0\
-lvtksqlite-7.0\
-lvtksys-7.0\
-lvtktiff-7.0\
-lvtkverdict-7.0\
-lvtkViewsContext2D-7.0\
-lvtkViewsCore-7.0\
-lvtkViewsInfovis-7.0\
#-lvtkViewsQt-7.0\
-lvtkzlib-7.0
}





